services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge